//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace CGM
{
	public enum ViewType {Text}
	
	//[Serializable]
	public class ResourceView : CGMView
	{	
		//[UnityEngine.SerializeField]
		ComponentWrapper view_component;
		
		//[UnityEngine.SerializeField]
		CGME.Resource view_resource;
		
		//[UnityEngine.SerializeField]
		ResourceType res_type;
		
		public void InitAsText(GameObject parent, CGME.Resource resource, ResourceType type){
		
			//view_component = (Component)parent.AddComponent<TextMesh>();
			view_component = (ComponentWrapper)new TextMeshWrapper();
			view_component.Init (parent);
			
			view_resource = resource;
			res_type = type;
		
		}
		
		public void Update(){
			string value = "default";
						
			switch (res_type){
			
				case ResourceType.Text:
					CGME.ResourceText restext;
					restext = (CGME.ResourceText)view_resource;
					value = restext.Value;
					break;
				case ResourceType.Number:
					CGME.ResourceNumber resnum;
					resnum = (CGME.ResourceNumber)view_resource;
					value = resnum.Value.ToString();
					break;
				case ResourceType.Bool:
					CGME.ResourceBool resbool;
					resbool = (CGME.ResourceBool)view_resource;
					value = resbool.Value.ToString();
					break;
				case ResourceType.Action:
					CGME.ResourceAction resact;
					resact = (CGME.ResourceAction)view_resource;
					value = resact.Value.CGType;
					break;
			
			}
			
			
			view_component.Update(value);
		
		}
		
		
	}
}

