//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class ResourceText : CGME.Resource
	{
		private string _value;
		
		public ResourceText(){
			cgtype = "Name";
			Value = "Value";
		}
//		public ResourceText(string name, string value, bool enabled = true){
//			
//			this.Name = name;
//			SetValue(value);
//			this.enabled = enabled;
//			
//		}
		
		public string Value{
			get{return _value;}
			set{_value = value;}
		}
		
		public override void Enable (bool enable)
		{
			this.enabled = enable;
		}
		
		public override string ToString(){
			return (cgtype + ": " + Value);
		}
		
		public void AddValue(string value){
			this._value+= " " + Value;
			DispatchEvent(EngineEvent.ModifyResource, null, null);
		}
		
		public void SetValue(string value){
			this._value = Value;
			DispatchEvent(EngineEvent.ModifyResource, null, null);
		}
		
		
		public override void SaveParameters(System.IO.BinaryWriter writer){
			writer.Write(_value);
			//action.Write(name);
		}
		
		public override void LoadParameters(System.IO.BinaryReader reader){
			_value = reader.ReadString();
		}
		
//		public override byte[] ToBytes(){
//			
//			if (_value == null) return null;
//			//byte[] myByteArray = new byte[10];
//			
//			System.IO.MemoryStream stream = new System.IO.MemoryStream();
//			System.IO.BinaryWriter writer = new System.IO.BinaryWriter(stream);
//			
//			writer.Write(_value);
//			return stream.ToArray();
//			
//		}
//		public override void Read(byte[] FromBytes){
//			
//			if (FromBytes == null) return;
//			
//			System.IO.MemoryStream stream = new System.IO.MemoryStream(FromBytes);
//			System.IO.BinaryReader reader = new System.IO.BinaryReader(stream);
//			
//			_value = reader.ReadString();
//			
//		}
		
	}
}

