//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public abstract class ActionSingleEffect : Action
	{
			
		public override void Enable(bool enable){
		
			this.enabled = enable;
			
			EnableResources(enable);
		}
		
		public override void Arm(){
			
			armed = true;
		}
		
		public override void Disarm(){
			armed = false;
		}
	}
}

