//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public static class CGFactory
	{

		public static CGObject CreateCGInstance(string s){
			//GameManager.DebugLog(s);
			Type t = Type.GetType(s);
			
			if (t == null) return null;
			
			//return null;
			return Activator.CreateInstance(t) as CGObject;
		}
	}
}

