//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public abstract class CGMObject
	{
		private static int ID_DEFINE;
		private string name;
		protected bool enabled;
		private int id;
		
		
		public string Name{get{return name;}set{name = value;}}		
		public bool Enabled{get{return enabled;}}
		public int Id{get{return id;}}
				
		public void SetId(){
			id = ID_DEFINE++;
		}
		
		public abstract void Enable(bool enable);
		public abstract CGMObject FindObject(int id);
		public abstract CGMObject FindObject(string name);
	}
}

