//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace CGME
{
	public static class Log
	{
		public static void Error(CGObject source, string s){
			Debug.LogError(source.CGType + " :: " + s);
		}
		
		public static void Warning(CGObject source, string s){
			Debug.LogWarning(source.CGType + " :: " + s);
		}
		
		public static void Print(CGObject source, string s){
			Debug.Log(source.CGType + " :: " + s);
		}
	}
}

