//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

namespace CGMEditor
{
	[CustomEditor(typeof(CGM.Deck))]
	public class DeckInspector : CGMObjectInspector
	{
	
		public override void DrawObject(CGM.CGMObject Target){
			
			CGM.Deck t = (CGM.Deck)target;
			t.CGME_Deck.CGType = EditorGUILayout.TextField("Type",t.CGME_Deck.CGType);
			Target.gameObject.name = t.CGME_Deck.CGType;
			
			t.visible_children = EditorGUILayout.Toggle("Deck View - visible children", t.visible_children);
			t.deny_reposition = EditorGUILayout.Toggle("Deck View  - deny reposition", t.deny_reposition );
			t.pile = EditorGUILayout.Toggle("Deck View  - pile format", t.pile );
			if (!t.pile){
				t.size = EditorGUILayout.FloatField("Deck View  - width", t.size);
				t.spread = EditorGUILayout.FloatField("Deck View - spread", t.spread);
			}
		}
	
	//	public override void OnInspectorGUI()
	//	{
	//		CGMEU.Card Target = (CGMEU.Card)target;
	//		
	//		Target.name = EditorGUILayout.TextField("Name", Target.name);
	//		EditorGUILayout.LabelField("Resources");
	//		foreach (CGMEU.Resource res in Target.Resources){
	//			EditorGUILayout.BeginHorizontal();
	//				res.name = EditorGUILayout.TextField(res.name);
	//				
	//				if (res.Resource_type ==  CGMEU.ResourceType.Number){
	//					CGME.ResourceNumber cgres = (CGME.ResourceNumber)res.CGME_Resource;
	//					cgres.Value = EditorGUILayout.IntField (cgres.Value);
	//				}
	//				else if (res.Resource_type ==  CGMEU.ResourceType.Text){
	//					CGME.ResourceText cgres = (CGME.ResourceText)res.CGME_Resource;
	//					cgres.Value = EditorGUILayout.TextField (cgres.Value);
	//				}
	//				else if (res.Resource_type ==  CGMEU.ResourceType.Bool){
	//					CGME.ResourceBool cgres = (CGME.ResourceBool)res.CGME_Resource;
	//					cgres.Value = EditorGUILayout.Toggle (cgres.Value);
	//				}
	//				else if (res.Resource_type ==  CGMEU.ResourceType.Action){
	//					CGME.ResourceAction cgres = (CGME.ResourceAction)res.CGME_Resource;
	//					//cgres.Value = EditorGUILayout.TextArea.Field (cgres.Value);
	//					EditorGUILayout.LabelField (cgres.Value.Name);
	//				}
	//				
	//			
	//			EditorGUILayout.EndHorizontal();
	//		}
	//		
	//		
	//		//EditorGUILayout.LabelField("Level", myTarget.Level.ToString());
	//	}
	}
}

