//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class ActionEditorNodeObjectValid : ActionEditorNode
	{
		public ActionEditorNodeObjectValid (CGME.Action act) : base(act)
		{

		}
		
		public override void DrawAsInspector(){
		
			base.DrawAsInspector();
		
			CGME.ActionConditionIsValid act = (action as CGME.ActionConditionIsValid);
		
			EditorGUILayout.BeginHorizontal();
			act.Source = (CGME.SelectionSource)Display.EnumPopup(this,"Source",act.Source);
			if (act.Source == CGME.SelectionSource.Type) 
				act.SourceString = Display.TextField(this,"Type", act.SourceString);
			EditorGUILayout.EndHorizontal();
		}
	}
}

