//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;


namespace CGMEditor
{
	public class ActionEditorNodeGroup : ActionEditorNode
	{
		
		private Rect button_rect;
		CGME.ActionDictionary dictionary;

		string[] action_names;

		private ActionEditorPopupWindow add_action_popup;
	
		public ActionEditorNodeGroup (CGME.Action act) : base(act)
		{
			dictionary = CGME.ActionDictionary.GetInstance();
			
			action_names = dictionary.GetNames();
			
			add_action_popup = ActionEditorPopupWindow.GetInstance();
		}
		
		public override void RepositionNodes (int level)
		{
			base.RepositionNodes (level);
			
			button_rect= new Rect(base.rectangle);
			
			button_rect.x 	   += button_rect.width  * 0.70f;
			button_rect.y 	   += button_rect.height * 0.70f;
			button_rect.width  *= 0.30f;
			button_rect.height *= 0.30f;
			
//			popup_position = new Rect(button_rect);
//			popup_position.height = 20f;
//			popup_position.width = 150f;
			
			
			
		}
		
		// return true if the action has changed
		public override bool DrawAsNode(){
			if (base.DrawAsNode() == true)
				return true;
			
			
			if (GUI.Button(button_rect,"+",standard_style)){
				
				add_action_popup.Build(button_rect,action_names, this);
				//add_action_popup.draw = true;
			}
			
			
			return  CheckPopup();		
		}
		
		public override void DrawAsInspector(){
			base.DrawAsInspector();
		}
		
		
		
		
		public bool CheckPopup(){
			if (add_action_popup.owner == this){
				//add_action_popup.Draw();
				int index = add_action_popup.clicked_index;
				
				if (index!= -1){
					//show_popup = false;
					(action as CGME.ActionGroup).
						AddAction(dictionary.GetAction(index));
					add_action_popup.Destroy();
					return true;
				}
				
			}
			
			return false;
		}
	
	// EOF =
	}
}

