//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class ActionEditorNodeSelect : ActionEditorNodeGroup
	{
		public ActionEditorNodeSelect (CGME.Action act) : base(act)
		{

		}
		
		public override void DrawAsInspector(){
		
			base.DrawAsInspector();
		
			CGME.ActionSelect action_select = (action as CGME.ActionSelect);
		
			
				EditorGUILayout.BeginHorizontal();
				{
					//action.Source = (CGME.SelectionSource)(EditorGUILayout.EnumPopup("Source", action.Source)) ;
					action_select.Source = (CGME.SelectionSource)(Display.EnumPopup(this,"Source", action_select.Source)) ;
					switch (action_select.Source){
					case CGME.SelectionSource.Type:
						//action.SourceCGType = EditorGUILayout.TextField("CGType",action.SourceCGType);
						action_select.SourceCGType = Display.TextField(this,"Type",action_select.SourceCGType);
						break;
					}
				}	
				EditorGUILayout.EndHorizontal();
				
				EditorGUILayout.BeginHorizontal();
				{
					action_select.Mode = (CGME.SelectionMode)(EditorGUILayout.EnumPopup("Mode", action_select.Mode));
					
					switch (action_select.Mode){
					case CGME.SelectionMode.Type:
						//action.TargetCGType = EditorGUILayout.TextField("CGType",action.TargetCGType);
						action_select.TargetCGType = Display.TextField(this,"CGType",action_select.TargetCGType);
						break;
						
					case CGME.SelectionMode.Index:
						//action.TargetIndex = EditorGUILayout.IntField("Index",action.TargetIndex);
						action_select.TargetIndex = Display.IntField(this,"Index",action_select.TargetIndex);
						break;
					}
				}	
				EditorGUILayout.EndHorizontal();
			
		}
	}
}

