//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

namespace CGMEditor
{
	public class ActionEditorNodeModifyResource : ActionEditorNode
	{
		public ActionEditorNodeModifyResource (CGME.Action act) : base(act)
		{
			
		}
		
		public override void DrawAsInspector(){
			
			base.DrawAsInspector();
			
			CGME.ActionModifyResource act = (action as CGME.ActionModifyResource);
			CGM.GameManager lib = GameObject.FindObjectOfType<CGM.GameManager>();
			
			EditorGUILayout.BeginHorizontal();
			{
				//action.Target 		= (CGME.ModifyParameter)EditorGUILayout.EnumPopup("Target",action.Target);
				//action.Target_Resource = EditorGUILayout.Popup("Resource Type",action.Target_Resource, lib.CGME_Lib.ResourceTypes());
				act.Target 		= (CGME.ResourceSource)Display.EnumPopup(this,"Target",act.Target);
				act.Target_Resource = Display.Popup(this,"Resource Type",act.Target_Resource, lib.CGME_Lib.ResourceTypes());
				
			}
			EditorGUILayout.EndHorizontal();
			
			//action.Operation 	= (CGME.ModifyOperation)EditorGUILayout.EnumPopup("Operation",action.Operation);
			act.Operation 	= (CGME.ModifyOperation)Display.EnumPopup(this,"Operation",act.Operation);
			
			
			EditorGUILayout.BeginHorizontal();
			{
				//action.Param1 		= (CGME.ModifyParameter)EditorGUILayout.EnumPopup("Resource 1",action.Param1);
				act.Param1 		= (CGME.ResourceSource)Display.EnumPopup(this,"Resource",act.Param1);
				if (act.Param1 == CGME.ResourceSource.FixedValue){
					
					CGME.Resource test = lib.CGME_Lib.GetResource(act.Target_Resource);
					if (test is CGME.ResourceBool) 
						//action.BoolMod = EditorGUILayout.Toggle("Boolean",action.BoolMod);
						act.BoolMod = Display.Toggle(this,"Boolean",act.BoolMod);
					else if (test is CGME.ResourceNumber) 
						act.NumberMod = Display.IntField(this,"Number",act.NumberMod);
					else if (test is CGME.ResourceText) 
						act.TextMod = Display.TextField(this,"Text",act.TextMod);
					
				}
				else
					act.Operation_Resource = Display.Popup(this,"Resource Type",act.Operation_Resource, lib.CGME_Lib.ResourceTypes());
			}
			EditorGUILayout.EndHorizontal();
		}
		
		
	}
}

