//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class ActionEditorNodeBufferSave : ActionEditorNode
	
	{
		public ActionEditorNodeBufferSave (CGME.Action act) : base(act)
		{

		}
		
		public override void DrawAsInspector(){
		
			base.DrawAsInspector();
		
			CGME.ActionBufferSave action_save = (action as CGME.ActionBufferSave);
		
				//action.Destination = EditorGUILayout.TextField("Destination", action.Destination);
				//action.Destination = Display.TextField(Target,"Destination", action.Destination);
				EditorGUILayout.BeginHorizontal();
			action_save.Selection = (CGME.SelectionSource)Display.EnumPopup(this,"Object",action_save.Selection);
			if (action_save.Selection == CGME.SelectionSource.Type) 
				action_save.typestring = Display.TextField(this,"Type",action_save.typestring);
				EditorGUILayout.EndHorizontal();
		
			}
	}
}

