//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class ActionEditorNodeBufferSize : ActionEditorNode
	{
		public ActionEditorNodeBufferSize (CGME.Action act) : base(act)
		{
		
		}
		
		public override void DrawAsInspector(){
		
			base.DrawAsInspector();
		
			CGME.ActionConditionBufferSize act = (action as CGME.ActionConditionBufferSize);
			
			act.Operation = (CGME.CompareOperation)Display.EnumPopup(this, "Operation",act.Operation);
			act.Value = Display.IntField(this,"Value",act.Value);
		}
	}
}

