//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class ActionEditorNodeDestroyObject : ActionEditorNode
	{
		public ActionEditorNodeDestroyObject (CGME.Action act) : base(act)
		{

		}
		
		public override void DrawAsInspector(){
		
			base.DrawAsInspector();
		
			CGME.ActionDestroyObject action_destroy = (action as CGME.ActionDestroyObject);
		
			EditorGUILayout.BeginHorizontal();
			action_destroy.Source = (CGME.SelectionSource)Display.EnumPopup(this,"Object",action_destroy.Source);
			if (action_destroy.Source == CGME.SelectionSource.Type) 
				action_destroy.SourceString = Display.TextField(this,"Type",action_destroy.SourceString);
			EditorGUILayout.EndHorizontal();
		}
	}
}

