//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class ActionEditorNodeCompareParents : ActionEditorNodeComparable
	{
		public ActionEditorNodeCompareParents (CGME.Action act) : base(act)
		{

		}
		
		public override void DrawAsInspector(){
		
			base.DrawAsInspector();
		
			CGME.ActionConditionCompareParent act = (action as CGME.ActionConditionCompareParent);
		
			act.Argument = (CGME.BinaryComparison)Display.EnumPopup(this,"Argument",act.Argument);
		}
	}
}

