//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace CGM
{
	public class Button : CGMObject
	{
		List<CGME.Resource> resources = new List<CGME.Resource>();
		
		protected override void Start(){
			base.Start ();
			
			RegisterResources();
			
		}
		
		protected override void RegisterResource(CGM.Resource res){
				resources.Add(res.CGME_Resource);
		}
		
		public override CGME.Resource[] GetCGMEResources(){
			return resources.ToArray();
		} 
		
				
		public override void SetObject(CGME.CGObject cgobj){
			return;
		}
		
		protected override void SetListener(){
			return;
		}

		protected override void OnMouseDown(){
			base.OnMouseDown();
			
			renderer.material.color = Color.gray;
			
		}
		
		protected override void OnMouseEnter(){
			base.OnMouseEnter();
		} 
		

		protected void OnMouseUp(){
			renderer.material.color = Color.white;
		}
		
		protected override void CleanUp(){
			// DO NOTHING
		}
		
		
	}
}

