//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class ActionIfThenElse : Action
	{
	
		public ActionIfThenElse() : base("If-Then-Else"){
		
			IF = new ActionGroup("IF");
			THEN = new ActionGroup("THEN");
			ELSE = new ActionGroup("ELSE");
			
		}

		protected ActionGroup IF = new ActionGroup();
		protected ActionGroup THEN = new ActionGroup();
		protected ActionGroup ELSE = new ActionGroup();
		
		public ActionGroup GetIF(){
			return IF;
		}
		public ActionGroup GetTHEN(){
			return THEN;
		}
		
		public ActionGroup GetELSE(){
			return ELSE;
		}
		
		public void SetIF(ActionGroup act){
			IF = act;
			IF.ParentAction = this;
		}
		public void SetTHEN(ActionGroup act){
			THEN = act;
			THEN.ParentAction = this;
		}
		
		public void SetELSE(ActionGroup act){
			ELSE = act;
			ELSE.ParentAction = this;
		}
		
		
			
		public override bool Effect(CGObject s, Actor p1, Actor p2){
			
			IF.ParentAction = this;
			THEN.ParentAction = this;
			ELSE.ParentAction = this;
						
			if (IF.Run (s,p1,p2)){
				THEN.Run (s,p1,p2);
			}
			else{
				GameManager.DebugLog("ELSE");
				ELSE.Run (s,p1,p2);
				
			}
			
			return true;
		}
		
		public override void Enable(bool enable){
			
			this.enabled = enable;
			
			//EnableResources(enable);
			
			IF.Enable(enable);
			THEN.Enable(enable);
			ELSE.Enable(enable);
			
		}
		
		public override void CopyFrom(Action copy){
			
			base.CopyFrom(copy);
			
			ActionIfThenElse copyite = copy as ActionIfThenElse	;		
			
			this.IF = CGFactory.CreateCGInstance(copyite.IF.GetType().ToString()) as CGME.ActionGroup;
			this.IF.CopyFrom (copyite.IF);
			
			this.THEN = CGFactory.CreateCGInstance(copyite.THEN.GetType().ToString()) as CGME.ActionGroup;
			this.THEN.CopyFrom (copyite.THEN);
			
			this.ELSE = CGFactory.CreateCGInstance(copyite.ELSE.GetType().ToString()) as CGME.ActionGroup;
			this.ELSE.CopyFrom (copyite.ELSE);
	
		}
		
		public override void ClearChildren(){
			
			IF.ClearChildren();
			THEN.ClearChildren();
			ELSE.ClearChildren();
		
		}
		
		public override void CleanupChildren(){
			IF.CleanupChildren();
			THEN.CleanupChildren();
			ELSE.CleanupChildren();
		}
	
	}
}

