//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class ActionEvent : Action
	{
		private CustomActionEvent custom_action;
		public CustomActionEvent CustomAction{
			get {return custom_action;}
			set {custom_action = value;}
		}
		
		public ActionEvent () : base("Custom Action")
		{
			custom_action = CustomActionEvent.FocusObject;
		}
		
		public override bool Effect (CGObject s, Actor p1, Actor p2)
		{
			manager.CommandCustomAction(custom_action, s, p1, p2);
			
			return true;
			
		}
		
		public override void SaveParameters(System.IO.BinaryWriter writer){
			base.SaveParameters(writer);
			
			writer.Write((Int32)custom_action);
		}	
		
		public override void LoadParameters(System.IO.BinaryReader reader){
			base.LoadParameters(reader);

			custom_action = (CustomActionEvent)reader.ReadInt32();
		}
		
		public override void CopyFrom(Action copy){
			base.CopyFrom(copy);
			
			custom_action = (copy as ActionEvent).custom_action;		
		}
		
		
		
	}
}

