//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public abstract class ActionTargetable : Action
	{
		private Actor _target;
		public Actor Target{get{return _target;} set{_target = value;}}
		
		public override void Enable(bool enable){
			
			actor.Enable(enable);
		}
		
		public override void Arm(){
			
			armed = true;
		}
		
		public override void Disarm(){
			armed = false;
		}
		
		public override Actor FindActor(string actor_name){
			return actor.GetActor(actor_name);
		}
		
		public override Actor FindActor(int id){	
			return actor.GetActor(id);
			
		}
	
	}
}

