//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class ActionBufferClear : Action
	{
		public ActionBufferClear () : base("Clear Buffer")
		{
		}
		
		public override bool Effect (CGObject s, Actor p1, Actor p2)
		{
			manager.CommandBufferClear ();
			
			return true;
		}
	}
}

