//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	//public enum BufferAction {Save, Load};
	
	public class ActionBufferSave : Action
	{
		
		public SelectionSource Selection;
		public string typestring;
		
		public ActionBufferSave (): base("Save to Buffer"){
		
			Selection = SelectionSource.Original;
			typestring = "Type Name";
		}
		public override bool Effect (CGObject s, Actor p1, Actor p2)
		{
			CGObject ob = GetFromSource(Selection, typestring, s, p1, p2);
			
			
			if (ob != null && ob is Actor){
					manager.CommandBufferPushSelection(ob as Actor);
					return true;
			}		
			
			Log.Warning(this, "Object not found or invalid");

			return false;
			
		}
		
		public override void SaveParameters (System.IO.BinaryWriter writer)
		{
			base.SaveParameters (writer);
			
			writer.Write ((Int32)Selection);
			writer.Write (typestring);
		}
		
		public override void LoadParameters (System.IO.BinaryReader reader)
		{
			base.LoadParameters (reader);
			
			Selection = (SelectionSource)reader.ReadInt32();
			typestring = reader.ReadString ();
		}
		
		public override void CopyFrom (Action copy)
		{
			base.CopyFrom (copy);
			
			Selection = (copy as ActionBufferSave).Selection;
			typestring = (copy as ActionBufferSave).typestring;
		}
	}
}

