//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class ActionArm : Action
	{
		public ActionArm() : base("Rearm Action"){
			
		}
	
		public override bool Effect (CGObject s, Actor p1, Actor p2)
		{
			Action Root = ParentAction.FindRoot();
			//GameManager.DebugLog(Root.CGType);
			if (Root != null){
				Root.Arm();
				Log.Print(this,"Rearming " + Root.CGType);
				return true	;
			}
			
			return false;
				
		}
		
	}
}

