//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.544
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
//using JokerEngine;

namespace CGME
{
	//[Serializable]
	public class Card : CGME.Actor

	{
		public Card(){
			//SetId();
			cgtype = "New Card";
			enabled = true;
		}
//		public Card(string name, bool enabled = true){
//			Name = name;
//			Enable (enabled);
//		}
//		

		public override CGObject AddChild(CGObject child){
		
			return null;
		}
		
		public override void RemoveChild(CGObject child){
			return;
		}
		
		public override void  EnableChildren(bool enable){
			return;
		}
		
		public override CGObject FindChildren(string name){

			return null;
		}
		
		public override CGObject FindChildren(int id){
			
			return null;
		}
		
		public override void StartChildren(){
			return;
		}
		
		

				                           
	}

}

