//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;

namespace CGMEditor
{
	public class WindowActionNode : EditorWindow
	{
		private static WindowActionNode window_instance;
		
		private ActionEditorNode Target;
		
		public static WindowActionNode Init(ActionEditorNode target){
						
			window_instance = (WindowActionNode )EditorWindow.GetWindow(typeof(WindowActionNode));
			window_instance.title = "Action Inspector";
			
			window_instance.Target = target;
			
			return window_instance;
			//window_instance.selected_action = window_instance.GetSelectedAction();
		
		}
		
		void OnGUI()
		{
			if (Target != null)
				Target.DrawAsInspector();
		
		}
	}
}

