//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace CGM
{
	[Serializable]
	public class CardTypeConfig
	{
		public string name;
		
		public Sprite card_frame;
		public Sprite card_back;
				
		public List <bool> resources_used = new List<bool>();
	}
}

