//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace CGM
{
	[Serializable]
	public class LibNode
	{
		public List<SerialNode> cards = new List<SerialNode>();
		//public serialNode[] actions;
		public List<SerialNode> resources = new List<SerialNode>();
		
		public void Clear(){
			cards.Clear();
			resources.Clear ();
		}
	}
}

