//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace CGM
{
	[Serializable]
	public class SerialNode
	{
	
		public string type_string;
		public byte[] data;
		
		//Only for Trees
		public int index;
		public List<int> children_indexes = new List<int>();
		//public int childCount;
		//public int indexOfFirstChild;
		
		//int[] index_of_child;
		

	}
}

