//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

namespace CGMEditor
{
	
	
	public class CGMWizard {
		
		[MenuItem ("GameObject/CGM/Create Bundle")]
		static void CreateWizard () {
			//ScriptableWizard.DisplayWizard<CGMWizard>("Create Bundle", "Create");
			OnWizardCreate ();
	
		}
		static void OnWizardCreate () {
			GameObject manager = new GameObject ("Manager");
			manager.AddComponent<CGM.GameManager>();
			
			GameObject game = new GameObject ("Game");
			game.AddComponent<CGM.Game>();
			
			GameObject player = new GameObject ("Player");
			player.AddComponent<CGM.Player>();
			player.transform.parent = game.transform;
			
			GameObject deck = new GameObject ("Deck");
			deck.AddComponent<CGM.Deck>();
			deck.transform.parent = player.transform;
			
			GameObject card = new GameObject ("Card");
			card.AddComponent<CGM.Card>();
			card.transform.parent = deck.transform;
			
			GameObject res = new GameObject ("Resource");
			res.AddComponent<CGM.Resource>();
			res.transform.parent = card.transform;
			
			GameObject phase = new GameObject ("Phase");
			phase.AddComponent<CGM.Phase>();
			phase.transform.parent = game.transform;
		}  
//		void OnWizardUpdate () {
//			helpString = "Create all the GameObjects you need to start CGM";
//		}   
	}
}

