//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

namespace CGMEditor
{
	public static class Display
	{
		public static string[] ResourceTypes = new string[]{"Action", "Bool", "Number", "Text"};

		public static void Label(string label){
			EditorGUILayout.LabelField(label);
		}


		public static string TextField(CGM.Action act, string label, string obj){
			string ret = EditorGUILayout.TextField(label,obj);
			//Debug.Log (ret + " " + obj);
			if (ret != obj)	act.SetSerialize(true);
			
			return ret;
			
		}
		
		public static Enum EnumPopup(CGM.Action act, string label, Enum obj){
			Enum ret = EditorGUILayout.EnumPopup(label, obj);
			
			if (ret != obj)	act.SetSerialize(true);
			
			return ret;
		
		}
		
		public static int IntField(CGM.Action act, string label, int obj){
			int ret = EditorGUILayout.IntField(label, obj);
			
			if (ret != obj)	act.SetSerialize(true);
			
			return ret;
			
		}
		
		public static int Popup(CGM.Action act, string label, int obj, string[] labels){
			int ret = EditorGUILayout.Popup(label,obj, labels);
			
			if (ret != obj)	act.SetSerialize(true);
			
			return ret;
			
		}
		
		public static bool Toggle(CGM.Action act, string label, bool obj){
			bool ret = EditorGUILayout.Toggle(label, obj);
			
			if (ret != obj)	act.SetSerialize(true);
			
			return ret;
			
		}
		
		public static string TextField(ActionEditorNode act, string label, string obj){
			string ret = EditorGUILayout.TextField(label,obj);
			//Debug.Log (ret + " " + obj););
			
			return ret;
			
		}
		
		public static Enum EnumPopup(ActionEditorNode act, string label, Enum obj){
			Enum ret = EditorGUILayout.EnumPopup(label, obj);
			
			return ret;
			
		}
		
		public static int IntField(ActionEditorNode act, string label, int obj){
			int ret = EditorGUILayout.IntField(label, obj);
			
			return ret;
			
		}
		
		public static int Popup(ActionEditorNode act, string label, int obj, string[] labels){
			int ret = EditorGUILayout.Popup(label,obj, labels);
			
			return ret;
			
		}
		
		public static bool Toggle(ActionEditorNode act, string label, bool obj){
			bool ret = EditorGUILayout.Toggle(label, obj);
			
			return ret;
			
		}
		
		
		
		
		
		
		
	
		
	}
}

