//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CGME
{
	public class ActionEndGame : Action
	{
		public ActionEndGame() : base("End Game"){
		
		}
		
		public override bool Effect(CGObject s, Actor p1, Actor p2){
			
			GameManager.GetInstance().CommandEndGame();
			
			return true;
		}
	}
}

